### ISSUE TITLE
Returning to the Elements list page from the Earth hyperlink is incorrect

### ISSUE THREAD

**Issue by ramirezc1** [McDonalc1/https-github.com-mcdonalc1-Elemental#5]
Overview: On the Earth Screen webpage 

Triggered Steps: Selecting "Return to Elements List" from the Earth webpage.

Actual Result: The Main Element webpage displays.

Expected Result: The Elements List webpage should be displayed.

Version: 96728590bf95c0fcc441d16411fe5848c5ccd851

**Comment by McDonalc1** [comment]
I have changed the hyperlink from index.html to list.html Please verify that the bug is quashed.

**Comment by ramirezc1** [comment]
Selecting "Return to Elements List" from the Earth web page does return to the Element List web page. Issue fixed
