### ISSUE TITLE
Image on Fire webpage is incorrect

### ISSUE THREAD

**Issue by ramirezc1** [McDonalc1/https-github.com-mcdonalc1-Elemental#7]
Overview: On the Fire webpage, the image for "Fire" is set to "Water".

Triggered Steps: Selecting "Fire" from the Elements List webpage.

Actual Result: The Fire displays the "Water" image.

Expected Result: The Fire web page should display the correct image, the "Fire" image

Version: 96728590bf95c0fcc441d16411fe5848c5ccd851

**Comment by McDonalc1** [comment]
I have changed the Image for the Fire Webpage from water.png to fire.png. Please verify that the bug is quashed.

**Comment by ramirezc1** [comment]
Image on Fire web page does display Fire element. Issue Fixed
