### ISSUE TITLE
Hyperlink of Water on Elements List webpage is incorrect

### ISSUE THREAD

**Issue by ramirezc1** [McDonalc1/https-github.com-mcdonalc1-Elemental#8]
Overview: On the Elements List webpage, the hyperlink for "Water" is linked to Earth webpage

Triggered Steps: Clicking on "Water" from the Elements List webpage.

Actual Result: The Earth web page displays. 

Expected Result: The Water web page should display. 

Version: 96728590bf95c0fcc441d16411fe5848c5ccd851

**Comment by McDonalc1** [comment]
I have changed the hyperlink for Water from earth.html to water.html. Please verify that the bug is quashed.

**Comment by ramirezc1** [comment]
Clicking on "Water" from the Elements List webpage displays Water web page. Issue fixed
