### ISSUE TITLE
Water webpage's name of element is incorrect

### ISSUE THREAD

**Issue by ramirezc1** [McDonalc1/https-github.com-mcdonalc1-Elemental#9]
Overview: On the Water web page, the element name is incorrectly set to "AIR"

Triggered Steps: Clicking on "Water" from the Elements List web page.

Actual Result: The Water web page is displayed with element name "AIR"

Expected Result: The Water web page is displayed with "WATER" element name

Version: 96728590bf95c0fcc441d16411fe5848c5ccd851

**Comment by McDonalc1** [comment]
I have changed the Element Header from AIR to WATER. Please verify that the bug is quashed.

**Comment by ramirezc1** [comment]
The Water web page is now displayed with correct "WATER" element name. Issue fixed.
